import { useState } from 'react'
import { Download, Play, FlaskConical } from 'lucide-react'
import { Titulo } from './App'
import { casos, ejecutarCaso, ordenCasos, type Caso, type Resultado } from './casos'

export function CasosPagina() {
  const [password, setPassword] = useState('')
  const [resultados, setResultados] = useState<Record<string, Resultado>>({})
  const [ejecutando, setEjecutando] = useState('')
  async function uno(c: Caso) { if (!password) return; setEjecutando(c.id); const r = await ejecutarCaso(c, password); setResultados(prev => ({ ...prev, [c.id]: r })); setEjecutando('') }
  async function todos() { if (!password || !window.confirm('La ejecución aprueba el documento 511, modifica 502 y elimina 509. ¿Continuar?')) return; setEjecutando('todos'); const nuevos: Record<string, Resultado> = {}; for (const c of ordenCasos) { const r = await ejecutarCaso(c, password); nuevos[c.id] = r; setResultados({ ...nuevos }) } setEjecutando('') }
  function exportar() { const lineas = ['# Ejecución de casos SecureDocs', '', `Fecha: ${new Date().toLocaleString('es-PE')}`, '', '| Caso | Esperado | Obtenido | Resultado |', '| --- | --- | --- | --- |', ...casos.map(c => { const r = resultados[c.id]; return `| ${c.id} | ${r?.esperado || `HTTP ${c.esperado}`} | ${(r?.obtenido || 'Sin ejecutar').replaceAll('|','/')} | ${r ? r.correcto ? 'Correcto' : 'Fallo' : 'Pendiente'} |` }), '', 'Los detalles completos y el registro de auditoría se consultan en el backend.']; const blob = new Blob([lineas.join('\n')], { type: 'text/markdown;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'casos-securedocs.md'; a.click(); URL.revokeObjectURL(url) }
  const completados = Object.values(resultados)
  return <><Titulo eyebrow="Verificación guiada" titulo="Panel de casos" descripcion="Ejecuta T1–T17 con cuentas demo y compara la respuesta real con la esperada." action={<button className="btn-ghost" onClick={exportar}><Download size={16} /> Exportar Markdown</button>} />
    <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Antes de ejecutar:</b> introduce la contraseña de las cuentas demo. Se usa solo en esta sesión de la página y no se almacena. El conjunto completo altera datos: T3 aprueba 511, T14 actualiza 502 y T6 elimina 509. Reinicia los datos demo antes de repetirlo.</div>
    <div className="card mb-6 flex flex-wrap items-end gap-3 p-5"><label className="min-w-56 flex-1"><span className="label">Contraseña demo</span><input type="password" autoComplete="off" className="field" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="btn-primary" disabled={!password || !!ejecutando} onClick={todos}><Play size={16} /> {ejecutando === 'todos' ? 'Ejecutando…' : 'Ejecutar todos'}</button><div className="pb-2 text-sm text-slate-500">{completados.filter(r => r.correcto).length} correctos · {completados.filter(r => !r.correcto).length} fallos</div></div>
    <div className="grid gap-3">{casos.map(c => { const r = resultados[c.id]; return <article key={c.id} className="card flex flex-wrap items-center gap-4 p-4"><div className="rounded-xl bg-cyan-50 p-3 text-[#145a72]"><FlaskConical size={19} /></div><div className="min-w-52 flex-1"><div className="flex items-center gap-2"><b>{c.id}</b><span className="text-sm text-slate-700">{c.descripcion}</span></div><p className="mt-1 text-xs text-slate-500">{c.usuario} · {c.metodo} {c.ruta}</p>{r && <p className="mt-2 text-xs text-slate-600">Esperado: {r.esperado} <br /> Obtenido: {r.obtenido} · {r.detalle}</p>}</div><span className={`badge ${!r ? 'bg-slate-100 text-slate-600' : r.correcto ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{!r ? 'Pendiente' : r.correcto ? 'Correcto' : 'Fallo'}</span><button className="btn-ghost" disabled={!password || !!ejecutando} onClick={() => uno(c)}>{ejecutando === c.id ? 'Ejecutando…' : 'Ejecutar'}</button></article> })}</div>
  </>
}
