import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Eye, FilePlus2, Pencil, RefreshCw, Search, Trash2, CheckCircle2 } from 'lucide-react'
import { api, errorTexto } from './api'
import { Titulo, Vacio } from './App'
import type { Documento, Usuario } from './types'

export function Documentos({ usuario, acceso }: { usuario: Usuario; acceso: (p: string) => boolean }) {
  const [documentos, setDocumentos] = useState<Documento[]>([])
  const [seleccionado, setSeleccionado] = useState<Documento | null>(null)
  const [modo, setModo] = useState<'ver' | 'crear' | 'editar' | null>(null)
  const [busqueda, setBusqueda] = useState('')
  const [error, setError] = useState('')
  const [aviso, setAviso] = useState('')
  const [ocupado, setOcupado] = useState(false)
  const [form, setForm] = useState({ titulo: '', descripcion: '', nivelConfidencialidad: 1 })
  const cargar = useCallback(async () => { try { setDocumentos((await api.get<Documento[]>('/documentos')).data); setError('') } catch (e) { setError(errorTexto(e)) } }, [])
  useEffect(() => { void cargar() }, [cargar])
  const filtrados = documentos.filter(d => `${d.titulo} ${d.departamento} ${d.estado}`.toLowerCase().includes(busqueda.toLowerCase()))
  function abrirCrear() { setForm({ titulo: '', descripcion: '', nivelConfidencialidad: 1 }); setSeleccionado(null); setModo('crear'); setError('') }
  function abrirEditar(doc: Documento) { setForm({ titulo: doc.titulo, descripcion: doc.descripcion, nivelConfidencialidad: doc.nivelConfidencialidad }); setSeleccionado(doc); setModo('editar'); setError('') }
  async function ver(doc: Documento) { try { setSeleccionado((await api.get<Documento>(`/documentos/${doc.id}`)).data); setModo('ver'); setError('') } catch (e) { setError(errorTexto(e)) } }
  async function guardar(e: FormEvent) { e.preventDefault(); setOcupado(true); try { if (modo === 'crear') await api.post('/documentos', form); else if (seleccionado) await api.put(`/documentos/${seleccionado.id}`, { titulo: form.titulo, descripcion: form.descripcion }); setModo(null); setAviso('Documento guardado correctamente'); await cargar() } catch (e) { setError(errorTexto(e)) } finally { setOcupado(false) } }
  async function actuar(doc: Documento, accion: 'eliminar' | 'aprobar') { if (!window.confirm(`¿Confirmas ${accion} “${doc.titulo}”?`)) return; try { if (accion === 'eliminar') await api.delete(`/documentos/${doc.id}`); else await api.post(`/documentos/${doc.id}/aprobar`); setModo(null); setAviso(accion === 'eliminar' ? 'Documento eliminado' : 'Documento aprobado'); await cargar() } catch (e) { setError(errorTexto(e)) } }
  return <><Titulo eyebrow="Biblioteca protegida" titulo="Documentos" descripcion="El listado contiene solo recursos visibles para tu rol y contexto actual." action={<div className="flex gap-2"><button className="btn-ghost" onClick={cargar}><RefreshCw size={16} /> Actualizar</button>{acceso('CREAR_DOCUMENTO') && <button className="btn-primary" onClick={abrirCrear}><FilePlus2 size={17} /> Nuevo documento</button>}</div>} />
    {error && <p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{aviso && <p role="status" className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{aviso}</p>}
    <div className="card mb-5 flex items-center gap-2 p-3"><Search size={18} className="text-slate-400" /><input className="w-full border-0 bg-transparent text-sm outline-none" aria-label="Buscar documentos" placeholder="Buscar por título, departamento o estado" value={busqueda} onChange={e => setBusqueda(e.target.value)} /></div>
    {filtrados.length === 0 ? <Vacio texto="No hay documentos visibles con estos criterios." /> : <div className="grid gap-4 xl:grid-cols-2">{filtrados.map(d => <article key={d.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><div className="mb-3 flex flex-wrap gap-2"><span className="badge bg-cyan-50 text-[#145a72]">{d.departamento}</span><span className="badge bg-slate-100 text-slate-600">Nivel {d.nivelConfidencialidad}</span></div><h2 className="text-lg font-bold">{d.titulo}</h2><p className="mt-1 line-clamp-2 text-sm text-slate-500">{d.descripcion}</p></div><span className={`badge ${d.estado === 'PUBLICADO' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{d.estado}</span></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><button className="btn-ghost" onClick={() => ver(d)}><Eye size={15} /> Ver</button>{acceso('MODIFICAR_DOCUMENTO') && <button className="btn-ghost" onClick={() => abrirEditar(d)}><Pencil size={15} /> Editar</button>}{acceso('APROBAR_DOCUMENTO') && d.estado === 'PENDIENTE' && <button className="btn-ghost" onClick={() => actuar(d, 'aprobar')}><CheckCircle2 size={15} /> Aprobar</button>}{acceso('ELIMINAR_DOCUMENTO') && <button className="btn-danger" onClick={() => actuar(d, 'eliminar')}><Trash2 size={15} /> Eliminar</button>}</div></article>)}</div>}
    {modo && <div className="fixed inset-0 z-30 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="card max-h-[90vh] w-full max-w-xl overflow-auto p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-[#145a72]">Documento {seleccionado?.id || 'nuevo'}</p><h2 className="mt-1 text-xl font-bold">{modo === 'ver' ? seleccionado?.titulo : modo === 'crear' ? 'Crear documento' : 'Editar documento'}</h2></div><button className="btn-ghost" onClick={() => setModo(null)}>Cerrar</button></div>{modo === 'ver' && seleccionado ? <div className="space-y-4 text-sm"><p className="whitespace-pre-wrap text-slate-700">{seleccionado.descripcion}</p><dl className="grid grid-cols-2 gap-3 rounded-lg bg-slate-50 p-4"><div><dt className="text-slate-500">Estado</dt><dd className="font-semibold">{seleccionado.estado}</dd></div><div><dt className="text-slate-500">Nivel</dt><dd className="font-semibold">{seleccionado.nivelConfidencialidad}</dd></div><div><dt className="text-slate-500">Departamento</dt><dd className="font-semibold">{seleccionado.departamento}</dd></div><div><dt className="text-slate-500">Propietario</dt><dd className="font-semibold">#{seleccionado.propietarioId}{seleccionado.propietarioId === usuario.id ? ' (tú)' : ''}</dd></div></dl></div> : <form onSubmit={guardar} className="space-y-4"><div><label className="label" htmlFor="titulo">Título</label><input id="titulo" className="field" required maxLength={200} value={form.titulo} onChange={e => setForm({ ...form, titulo: e.target.value })} /></div><div><label className="label" htmlFor="descripcion">Descripción</label><textarea id="descripcion" className="field min-h-32" required value={form.descripcion} onChange={e => setForm({ ...form, descripcion: e.target.value })} /></div>{modo === 'crear' && <div><label className="label" htmlFor="nivel">Nivel de confidencialidad</label><select id="nivel" className="field" value={form.nivelConfidencialidad} onChange={e => setForm({ ...form, nivelConfidencialidad: Number(e.target.value) })}>{[0,1,2,3,4,5].map(n => <option key={n} value={n}>{n}</option>)}</select></div>}<p className="text-xs text-slate-500">El backend vuelve a evaluar RBAC y ABAC al guardar.</p><button className="btn-primary" disabled={ocupado}>{ocupado ? 'Guardando…' : 'Guardar documento'}</button></form>}</div></div>}
  </>
}
